########################################################################
# How to create a YAML issue template form in your repository          #
########################################################################
# To use a YAML issue form in your repository, you must create a new
# file and add it to the .github/ISSUE_TEMPLATE folder in your
# repository by typing the full path to the new file in when prompted
# for a new file's name.
#
# If, for example, you wanted to create the bug.yaml form to add to your
# repository, click on the <> Code tab, then click on the "Add file"
# button, click on "Create new file", and then type this into the window
# that pops up: .github/ISSUE_TEMPLATE/bug.yaml
#
# Note that you won't need to get rid of your Markdown issue template.
########################################################################
# Required top-level fields                                            #
########################################################################
# The name is a string that's unique across all templates:
name: Issue Template Cheat Sheet
# The description is a string that is no more than 200 characters long
# that describes the intended use for this template:
description: This is a cheat sheet for creating issue forms in YAML.
title: "[CHEAT SHEET]: "
# The labels are an array or comma-delimited string of labels that will
# automatically be assigned to this issue:
# labels must be  defined in all repos
labels: ["patch", "backend"]
assignees:
  - stjop-avetisyan
body:
  - type: markdown
    attributes:
      value: |
        Issue that tequity asked for a patch.
  - type: dropdown
    id: project
    attributes:
      label: Which Project/s need to patch?
      description: Select at minimum one project.
      options:
        - adapter
        - rgs
        - back-office
        - connector
        - rng
        - demo-casino
        - websocket
        - promo
        - shared
      multiple: true
    validations:
      required: true
  # CHECKBOX:
  - type: checkboxes
    id: checkboxes
    attributes:
      label: What kinds of M&Ms do you like?
      description: You may select more than one.
      options:
        - label: Green
        - label: Orange
        - label: Red
        - label: Yellow
  - type: checkboxes
    id: checkboxes_multiple_with_required_item
    attributes:
      label: What kinds of M&Ms do you like?
      description: You may select more than one.
      options:
        - label: Green
          required: true
        - label: Orange
        - label: Red
        - label: Yellow
  # DROPDOWN:
  - type: dropdown
    id: download
    attributes:
      label: How did you download the software?
      options:
        - apt-get
        - Built from source
        - Homebrew
        - MacPorts
    validations:
      required: true
  # INPUT:
  - type: input
    id: prevalence
    attributes:
      label: Bug prevalence
      description: "How often do you or others encounter this bug?"
      placeholder: "Whenever I visit the user account page."
    validations:
      required: false
  # MARKDOWN:
  - type: markdown
    attributes:
      value: |
        Issue that tequity asked for a patch.

  # MARKDOWN WITH MULTI-LINE CONTENT:
  - type: markdown
    id: markdown_with_multiline_content
    attributes:
     value: |
        ## Welcome!
        This type of entry can be used to communicate with the user
        without asking for any input.
  - type: markdown
    id: markdown_with_footnotes
    attributes:
      value: |
        This is the first footnote link[^1].
        This is the second footnote link[^2].
        This is the third footnote link[^note].
        [^1]: This is the first footnote.
        [^2]: This is the second footnote. It's a multi-line footnote.
          Newlines should be indented with 2 spaces.
        [^note]: This is the third footnote. It's a named footnote that
          renders with numbers just like simple footnotes do, but the
          name allows for easier identification and linking. 
     
     

###################################################
  - type: input
    id: thread-url
    attributes:
      label: THREAD URL
      description: Please provide a link to the thread
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Short description (optional)
      placeholder: Anything else you want to add?
    validations:
      required: false
